# Generated by Django 6.0.6 on 2026-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [ # Every migration can contain multiple operations
        migrations.CreateModel(
            name='Product', # Table name
            fields=[ # Table fields/attributes
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.URLField(max_length=2083)),
            ],
        ),
    ]
